package com.iyunhe.pojo;

public class TbBookPic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book_pic.pic_id
     *
     * @mbg.generated Thu Aug 16 22:00:51 CST 2018
     */
    private Integer picId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book_pic.book_id
     *
     * @mbg.generated Thu Aug 16 22:00:51 CST 2018
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_book_pic.pic_name
     *
     * @mbg.generated Thu Aug 16 22:00:51 CST 2018
     */
    private String picName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book_pic.pic_id
     *
     * @return the value of tb_book_pic.pic_id
     *
     * @mbg.generated Thu Aug 16 22:00:51 CST 2018
     */
    public Integer getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book_pic.pic_id
     *
     * @param picId the value for tb_book_pic.pic_id
     *
     * @mbg.generated Thu Aug 16 22:00:51 CST 2018
     */
    public void setPicId(Integer picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book_pic.book_id
     *
     * @return the value of tb_book_pic.book_id
     *
     * @mbg.generated Thu Aug 16 22:00:51 CST 2018
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book_pic.book_id
     *
     * @param bookId the value for tb_book_pic.book_id
     *
     * @mbg.generated Thu Aug 16 22:00:51 CST 2018
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_book_pic.pic_name
     *
     * @return the value of tb_book_pic.pic_name
     *
     * @mbg.generated Thu Aug 16 22:00:51 CST 2018
     */
    public String getPicName() {
        return picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_book_pic.pic_name
     *
     * @param picName the value for tb_book_pic.pic_name
     *
     * @mbg.generated Thu Aug 16 22:00:51 CST 2018
     */
    public void setPicName(String picName) {
        this.picName = picName;
    }
}